version: "3.2"
services:
  socrates:
    container_name: socrates
    image: moviedomfo/express_orders
    ports:
      - 3025:${PORT}
    environment:
      - SERVER_NAME="Socrates Orders API  ${PORT}"
    networks:
      net_eco:
        ipv4_address: 172.21.0.13
  ulises:
    image: moviedomfo/express_orders
    container_name: ulises
    ports:
      - 3026:${PORT}

    environment:
      - SERVER_NAME="Ulises Orders API ${PORT}"
    networks:
      net_eco:
        ipv4_address: 172.21.0.14

  # nginx:
  #   image: nginx:latest
  #   restart: always
  #   build:
  #     context: ./nginx
  #   ports:
  #     - 7000:80
  #     - 443:443
  #   networks:
  #     net_pelsoft:
  #       ipv4_address: 172.20.0.5

# networking for the Redis container
networks:
  net_eco:
    ipam:
      #driver: default
      config:
        - subnet: 172.21.0.0/16
