version: "3.2"
services:
  socrates:
    container_name: socrates
    image: moviedomfo/express_orders
    ports:
      - 3035:${APP_PORT}
    environment:
      - SERVER_NAME="Socrates Orders API  ${APP_PORT}"
    networks:
      net_eco:
        ipv4_address: 172.21.0.13
    volumes:
      - /e/volumens/express/orders:/app/files
  ulises:
    image: moviedomfo/express_orders
    container_name: ulises
    ports:
      - 3036:${APP_PORT}

    environment:
      - SERVER_NAME="Ulises Orders API ${APP_PORT}"
    networks:
      net_eco:
        ipv4_address: 172.21.0.14
    volumes:
      - /e/volumens/express/orders:/app/files
# networking for the Redis container
networks:
  net_eco:
    ipam:
      #driver: default
      config:
        - subnet: 172.21.0.0/16
