export class OrderBE {
  public OrderId: string;
  public PersonId: string;
  public Department: string;
  /**date when order was generated by the customer */
  public GeneratedDate: Date;
  public OrderDetail: OrderDetailsBE[];
  
  public Status: string;
}

export class OrderDetailsBE {
  public ProductId: number;
  public Quantity: number;
  public Unit: string;
}
