version: '3.2'
services:
  redis:
    container_name: 'nginx-pelsoft'
    image: nginx:latest
    restart: always
    ports:
      - 6001:80
      - 443:443
    volumes:
      - /e/volumens/nginx/default.conf:/etc/nginx/conf.d/default.conf
 