apiVersion: v1
kind: PersistentVolume
metadata:
  name: files-eco-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/d/volumes/eco/files
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Clase de almacenamiento explícita
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-eco-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: files-eco-pv  # Vincula explícitamente al PV logs1-pv
  storageClassName: manual  
