export class OrderBE {
  public ExternalOrderId : string
  public OrderId: number;
  public PersonId: string;
  public Department: string;
  /**date when order was generated by the customer */
  public CreatedDate: Date;
  public OrderDetail: OrderDetailsBE[];
  
  public Status: string;
}

export class OrderDetailsBE {
  public ProductId: number;
  public Quantity: number;
  public Unit: string;
}
